### ISSUE TITLE
Is there any manner to add Gremlin steps to definitions.yml?

### ISSUE THREAD

**Issue by codingalone** [babbel/grumlin#60]
Hi!

I added some steps to `definitions.yml` on my laptop that are not defined in the main branch of this repository (like `none` and `option`).

They seem to work fine on my local server!

But to use those steps in a production app built from the latest gem, I understand I need either to

- get the file merged to this repository or
- do some hack to overwrite the definition file or override the [definitions method](https://github.com/babbel/grumlin/blob/main/lib/grumlin.rb#L148) to read an external file

Can I just simply create a PR to merge the definitions file or is there any other desirable way to realize additional Gremlin steps?

Thanks :)

**Comment by driv3r** [comment]
Hey @codingalone person who have more knowledge on the subject is on holidays atm, he should get back to you as soon as he's back :+1: 

Still if you have a working example & it's not an issue, personally I would just submit PR in meantime ;-)

**Comment by zhulik** [comment]
Hey @codingalone, please feel free to open a PR.

**Comment by codingalone** [comment]
@zhulik @driv3r Thank both of you for the comments! I'll send a PR :)

**Comment by codingalone** [comment]
Sent a PR #62 regarding this issue
